import { StyleSheet } from 'react-native';

// Light theme colors
const lightColors = {
  gradient: ['white', '#FFE4C4'],
  background: {
    primary: '#FFFFFF',
    secondary: '#F5F5F5',
    tertiary: '#EEEEEE',
    cardHighlight: '#FFF5F5',
    favorite: 'rgba(255, 255, 255, 0.85)',
    statsBar: 'rgba(255, 255, 255, 0.7)',
  },
  text: {
    primary: '#4E342E',
    secondary: '#5D4037',
    tertiary: '#6D4C41',
    details: '#795548',
    productName: '#3E2723',
    price: '#616161',
    discountedPrice: '#388E3C',
    viewDetails: '#616161',
  },
  accent: {
    primary: '#FF6B6B',
    secondary: '#8D6E63',
    tertiary: '#A1887F',
    actionButton: '#795548',
    retryButton: '#8D6E63',
  },
  border: '#F5F5F5',
  shadow: {
    color: '#000',
    colorLight: '#9E9E9E',
  },
  discount: {
    background: '#fce4ec',
    text: '#e91e63',
  },
  icon: {
    primary: '#5D4037',
    secondary: '#6D4C41',
    placeholder: '#a0a0a0',
    priceIcon: '#388E3C',
  },
};

// Dark theme colors
const darkColors = {
  gradient: ['#121212', '#2D1E10'],
  background: {
    primary: '#1E1E1E',
    secondary: '#2D2D2D',
    tertiary: '#383838',
    cardHighlight: '#2A1A1A',
    favorite: 'rgba(30, 30, 30, 0.85)',
    statsBar: 'rgba(30, 30, 30, 0.7)',
  },
  text: {
    primary: '#E0E0E0',
    secondary: '#D7CCC8',
    tertiary: '#BCAAA4',
    details: '#A1887F',
    productName: '#E0E0E0',
    price: '#BCAAA4',
    discountedPrice: '#81C784',
    viewDetails: '#BCAAA4',
  },
  accent: {
    primary: '#FF8080',
    secondary: '#A1887F',
    tertiary: '#BCAAA4',
    actionButton: '#A1887F',
    retryButton: '#8D6E63',
  },
  border: '#2D2D2D',
  shadow: {
    color: '#000',
    colorLight: '#000',
  },
  discount: {
    background: '#4A1A2E',
    text: '#F48FB1',
  },
  icon: {
    primary: '#D7CCC8',
    secondary: '#BCAAA4',
    placeholder: '#757575',
    priceIcon: '#81C784',
  },
};

// Generate styles for light theme
const createLightStyles = () => StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    paddingTop: 60,
    paddingBottom: 15,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  backButton: {
    position: 'absolute',
    left: 15,
    top: 55,
    zIndex: 10,
  },
  titleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: 24,
    fontWeight: '600',
    color: lightColors.text.primary,
    textAlign: 'center',
  },
  countBadge: {
    backgroundColor: lightColors.accent.primary,
    borderRadius: 20,
    minWidth: 28,
    height: 28,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
    paddingHorizontal: 8,
  },
  countText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 14,
  },
  favoriteStatsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: lightColors.background.statsBar,
    marginHorizontal: 15,
    marginBottom: 15,
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderRadius: 12,
    shadowColor: lightColors.shadow.color,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 2,
  },
  favoriteStatsText: {
    fontSize: 15,
    color: lightColors.text.secondary,
    fontWeight: '500',
    marginLeft: 10,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingBottom: 50,
  },
  loadingText: {
    color: lightColors.text.tertiary,
    marginTop: 15,
    fontSize: 16,
    fontWeight: '500',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
    paddingBottom: 50,
  },
  emptyTitle: {
    fontSize: 22,
    fontWeight: '600',
    color: lightColors.text.secondary,
    marginBottom: 10,
  },
  emptyText: {
    fontSize: 16,
    color: lightColors.text.details,
    textAlign: 'center',
    marginBottom: 30,
    lineHeight: 22,
  },
  shopButton: {
    backgroundColor: lightColors.accent.actionButton,
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 30,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    shadowColor: lightColors.shadow.color,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 6,
  },
  shopButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 17,
  },
  retryButton: {
    backgroundColor: lightColors.accent.retryButton,
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 30,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    shadowColor: lightColors.shadow.color,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 6,
  },
  retryButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 17,
  },
  listContent: {
    paddingHorizontal: 15,
    paddingTop: 5,
    paddingBottom: 30,
  },
  productCard: {
    marginBottom: 18,
    borderRadius: 16,
    backgroundColor: lightColors.background.primary,
    shadowColor: lightColors.shadow.colorLight,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 4,
    overflow: 'hidden',
  },
  productContent: {
    flexDirection: 'row',
    padding: 12,
  },
  imageContainer: {
    position: 'relative',
    marginRight: 12,
  },
  productImage: {
    width: 100,
    height: 110,
    borderRadius: 12,
    backgroundColor: lightColors.background.secondary,
  },
  noProductImage: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: lightColors.background.tertiary,
  },
  favoriteIndicator: {
    position: 'absolute',
    bottom: 8,
    left: 8,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: lightColors.background.favorite,
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 8,
  },
  favoriteText: {
    fontSize: 11,
    fontWeight: '600',
    color: lightColors.accent.primary,
    marginLeft: 4,
  },
  productDetails: {
    flex: 1,
    justifyContent: 'space-between',
  },
  productName: {
    fontSize: 17,
    fontWeight: '600',
    color: lightColors.text.productName,
    marginBottom: 4,
    lineHeight: 22,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 10,
    marginBottom: 8,
  },
  infoChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: lightColors.background.secondary,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    gap: 5,
  },
  viewDetailsContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginTop: 15,
  },
  viewDetailsText: {
    fontSize: 13,
    color: lightColors.text.viewDetails,
    marginRight: 2,
    fontWeight: '500',
  },
  removeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: lightColors.background.cardHighlight,
    borderTopWidth: 1,
    borderTopColor: lightColors.border,
    paddingVertical: 10,
  },
  removeText: {
    fontSize: 14,
    fontWeight: '500',
    color: lightColors.accent.primary,
    marginLeft: 6,
  },
  priceContainer: {
    marginLeft: 5,
    justifyContent: 'center',
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 2,
    flexWrap: 'wrap',
  },
  originalPrice: {
    fontSize: 13,
    color: '#777',
    textDecorationLine: 'line-through',
    marginRight: 6,
  },
  discountedPrice: {
    fontSize: 14.5,
    fontWeight: 'bold',
    color: lightColors.text.discountedPrice,
  },
  regularPrice: {
    fontSize: 14,
    fontWeight: '500',
    color: lightColors.text.price,
  },
  discountTag: {
    backgroundColor: lightColors.discount.background,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  discountValue: {
    fontSize: 11,
    color: lightColors.discount.text,
    fontWeight: 'bold',
  },
});

// Generate styles for dark theme
const createDarkStyles = () => StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    paddingTop: 60,
    paddingBottom: 15,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  backButton: {
    position: 'absolute',
    left: 15,
    top: 55,
    zIndex: 10,
  },
  titleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: 24,
    fontWeight: '600',
    color: darkColors.text.primary,
    textAlign: 'center',
  },
  countBadge: {
    backgroundColor: darkColors.accent.primary,
    borderRadius: 20,
    minWidth: 28,
    height: 28,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
    paddingHorizontal: 8,
  },
  countText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 14,
  },
  favoriteStatsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: darkColors.background.statsBar,
    marginHorizontal: 15,
    marginBottom: 15,
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderRadius: 12,
    shadowColor: darkColors.shadow.color,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 2,
  },
  favoriteStatsText: {
    fontSize: 15,
    color: darkColors.text.secondary,
    fontWeight: '500',
    marginLeft: 10,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingBottom: 50,
  },
  loadingText: {
    color: darkColors.text.tertiary,
    marginTop: 15,
    fontSize: 16,
    fontWeight: '500',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
    paddingBottom: 50,
  },
  emptyTitle: {
    fontSize: 22,
    fontWeight: '600',
    color: darkColors.text.secondary,
    marginBottom: 10,
  },
  emptyText: {
    fontSize: 16,
    color: darkColors.text.details,
    textAlign: 'center',
    marginBottom: 30,
    lineHeight: 22,
  },
  shopButton: {
    backgroundColor: darkColors.accent.actionButton,
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 30,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    shadowColor: darkColors.shadow.color,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 6,
  },
  shopButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 17,
  },
  retryButton: {
    backgroundColor: darkColors.accent.retryButton,
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 30,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    shadowColor: darkColors.shadow.color,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 6,
  },
  retryButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 17,
  },
  listContent: {
    paddingHorizontal: 15,
    paddingTop: 5,
    paddingBottom: 30,
  },
  productCard: {
    marginBottom: 18,
    borderRadius: 16,
    backgroundColor: darkColors.background.primary,
    shadowColor: darkColors.shadow.colorLight,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 4,
    overflow: 'hidden',
  },
  productContent: {
    flexDirection: 'row',
    padding: 12,
  },
  imageContainer: {
    position: 'relative',
    marginRight: 12,
  },
  productImage: {
    width: 100,
    height: 110,
    borderRadius: 12,
    backgroundColor: darkColors.background.secondary,
  },
  noProductImage: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: darkColors.background.tertiary,
  },
  favoriteIndicator: {
    position: 'absolute',
    bottom: 8,
    left: 8,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: darkColors.background.favorite,
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 8,
  },
  favoriteText: {
    fontSize: 11,
    fontWeight: '600',
    color: darkColors.accent.primary,
    marginLeft: 4,
  },
  productDetails: {
    flex: 1,
    justifyContent: 'space-between',
  },
  productName: {
    fontSize: 17,
    fontWeight: '600',
    color: darkColors.text.productName,
    marginBottom: 4,
    lineHeight: 22,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 10,
    marginBottom: 8,
  },
  infoChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: darkColors.background.secondary,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    gap: 5,
  },
  viewDetailsContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginTop: 15,
  },
  viewDetailsText: {
    fontSize: 13,
    color: darkColors.text.viewDetails,
    marginRight: 2,
    fontWeight: '500',
  },
  removeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: darkColors.background.cardHighlight,
    borderTopWidth: 1,
    borderTopColor: darkColors.border,
    paddingVertical: 10,
  },
  removeText: {
    fontSize: 14,
    fontWeight: '500',
    color: darkColors.accent.primary,
    marginLeft: 6,
  },
  priceContainer: {
    marginLeft: 5,
    justifyContent: 'center',
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 2,
    flexWrap: 'wrap',
  },
  originalPrice: {
    fontSize: 13,
    color: '#999',
    textDecorationLine: 'line-through',
    marginRight: 6,
  },
  discountedPrice: {
    fontSize: 14.5,
    fontWeight: 'bold',
    color: darkColors.text.discountedPrice,
  },
  regularPrice: {
    fontSize: 14,
    fontWeight: '500',
    color: darkColors.text.price,
  },
  discountTag: {
    backgroundColor: darkColors.discount.background,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  discountValue: {
    fontSize: 11,
    color: darkColors.discount.text,
    fontWeight: 'bold',
  },
});

export const lightTheme = {
  colors: lightColors,
  styles: createLightStyles(),
};

export const darkTheme = {
  colors: darkColors,
  styles: createDarkStyles(),
};
